//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProBGApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request()
        {
            this.StaffRequests = new HashSet<StaffRequest>();
        }
    
        public int RequestId { get; set; }
        public string Submitter { get; set; }
        public string Email { get; set; }
        public System.DateTime SubmissionDate { get; set; }
        public System.TimeSpan SubmissionTime { get; set; }
        public string Ward { get; set; }
        public string WardMatron { get; set; }
        public string ConsideredOptions { get; set; }
        public string Status { get; set; }
        public int ShiftId { get; set; }
    
        public virtual Shift Shift { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaffRequest> StaffRequests { get; set; }
    }
}
