//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProBGApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffRequest
    {
        public int StaffRequestsId { get; set; }
        public int Requests_RequestId { get; set; }
        public int Staff_StaffId { get; set; }
        public string WardMatron { get; set; }
        public string Submitter { get; set; }
    
        public virtual Request Request { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
